server:
  port: 8080

spring:
  application:
    name: pensiones-service

management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true

info:
  app:
    name: Pensiones Service
    description: Afiliados al Sistema General de Pensiones de Colombia
    version: 1.0.0

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true

logging:
  level:
    com.platform.pensiones: DEBUG
